#-------------------------------
# General Site Settings

title: Mao Mao CV Blog
description: AI tools and reference management # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/galada"
url: "https://MaoMaoCV.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Mao Mao
author-avatar: 09.jpg # Avatar image which will be showing in the posts


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/mao_mao_mao_mao/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle

# #-------------------------------
# # Code Block Copy Button
# seo:
#   title: Example Developer Portal
#   description: Learn how to work with Example APIs
# copyCodeSnippet:
#   enable: true
#   buttonText: Copy
#   tooltipText: Copy code to clipboard
#   toasterText: Copied! Thank you for using moamaocv.github.io!
#   toasterDuration: 1500

#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: flase # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: G-HB7D85S8XJ # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 21
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
